target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  
  # Google
  pod 'GoogleSignIn'
  
  # Firebase
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
   config.build_settings['CODE_SIGN_IDENTITY'] = "Don't Code Sign"
   config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
   config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
   config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
  end
 end
end
